#server(eureka 默认端口为：8761)
server:
  port: 8761
#spring
spring:
  security:
    user:
      name: eureka
      password: eureka
  application:
    name: zzb-eureka
 # eureka
eureka:
  client:
    register-with-eureka: true # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetch-registry: false #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false。
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
